# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Automatically @generated Cargo.toml for the Rust crate rs_bindings_from_cc_generate_struct_and_union.

[package]
name = "rs_bindings_from_cc_generate_struct_and_union"
edition.workspace = true

license-file.workspace = true
repository.workspace = true
categories.workspace = true

[lib]
path = "../../../../rs_bindings_from_cc/generate_bindings/generate_struct_and_union.rs"

[dependencies]
cpp_type_name = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/cpp_type_name", package = "rs_bindings_from_cc_cpp_type_name"}
generate_comment = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/generate_comment", package = "rs_bindings_from_cc_generate_comment"}
arc_anyhow = { path = "../../../../cargo/common/arc_anyhow"}
code_gen_utils = { path = "../../../../cargo/common/code_gen_utils"}
crubit_feature = { path = "../../../../cargo/common/crubit_feature"}
error_report = { path = "../../../../cargo/common/error_report"}
ir = { path = "../../../../cargo/rs_bindings_from_cc/ir", package = "rs_bindings_from_cc_ir"}
database = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/database/database", package = "rs_bindings_from_cc_database"}
flagset.workspace = true
itertools.workspace = true
proc-macro2.workspace = true
quote.workspace = true
