# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
[book]
authors = ["Crubit Team"]
language = "en"
src = "docs"
title = "Crubit Documentation"

[preprocessor.tabs]

[output.html]
additional-css = ["docs/theme/tabs.css"]
additional-js = ["docs/theme/tabs.js"]
