# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

[toolchain]
channel = "nightly"
components = ["rustc-dev", "llvm-tools", "rustfmt"]
