# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Automatically @generated Cargo.toml for the Rust crate kythe_metadata.

[package]
name = "kythe_metadata"
edition.workspace = true

license-file.workspace = true
repository.workspace = true
categories.workspace = true

[lib]
path = "../../../common/kythe_metadata.rs"

doctest = false

[dependencies]
token_stream_printer = { path = "../../../cargo/common/token_stream_printer"}
anyhow.workspace = true
base64.workspace = true
serde.workspace = true
serde_json.workspace = true
[dev-dependencies]
googletest.workspace = true
