# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Automatically @generated Cargo.toml for the Rust crate rs_bindings_from_cc_generate_comment.

[package]
name = "rs_bindings_from_cc_generate_comment"
edition.workspace = true

license-file.workspace = true
repository.workspace = true
categories.workspace = true

[lib]
path = "../../../../rs_bindings_from_cc/generate_bindings/generate_comment.rs"

doctest = false

[dependencies]
code_gen_utils = { path = "../../../../cargo/common/code_gen_utils"}
crubit_feature = { path = "../../../../cargo/common/crubit_feature"}
error_report = { path = "../../../../cargo/common/error_report"}
ffi_types = { path = "../../../../cargo/common/ffi_types"}
ir = { path = "../../../../cargo/rs_bindings_from_cc/ir", package = "rs_bindings_from_cc_ir"}
database = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/database/database", package = "rs_bindings_from_cc_database"}
itertools.workspace = true
proc-macro2.workspace = true
quote.workspace = true
[dev-dependencies]
generate_bindings = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/generate_bindings", package = "rs_bindings_from_cc_generate_bindings"}
generate_comment = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/generate_comment", package = "rs_bindings_from_cc_generate_comment"}
arc_anyhow = { path = "../../../../cargo/common/arc_anyhow"}
error_report = { path = "../../../../cargo/common/error_report"}
ffi_types = { path = "../../../../cargo/common/ffi_types"}
token_stream_matchers = { path = "../../../../cargo/common/token_stream_matchers"}
ir = { path = "../../../../cargo/rs_bindings_from_cc/ir", package = "rs_bindings_from_cc_ir"}
ir_matchers = { path = "../../../../cargo/rs_bindings_from_cc/ir_matchers", package = "rs_bindings_from_cc_ir_matchers"}
ir_testing = { path = "../../../../cargo/rs_bindings_from_cc/ir_testing", package = "rs_bindings_from_cc_ir_testing"}
database = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/database/database", package = "rs_bindings_from_cc_database"}
googletest.workspace = true
quote.workspace = true
