# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Automatically @generated Cargo.toml for the Rust crate rs_bindings_from_cc_generate_bindings.

[package]
name = "rs_bindings_from_cc_generate_bindings"
edition.workspace = true

license-file.workspace = true
repository.workspace = true
categories.workspace = true

[lib]
path = "../../../../rs_bindings_from_cc/generate_bindings/lib.rs"

doctest = false

[dependencies]
cpp_type_name = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/cpp_type_name", package = "rs_bindings_from_cc_cpp_type_name"}
generate_comment = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/generate_comment", package = "rs_bindings_from_cc_generate_comment"}
generate_enum = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/generate_enum", package = "rs_bindings_from_cc_generate_enum"}
generate_function = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/generate_function", package = "rs_bindings_from_cc_generate_function"}
generate_function_thunk = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/generate_function_thunk", package = "rs_bindings_from_cc_generate_function_thunk"}
generate_struct_and_union = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/generate_struct_and_union", package = "rs_bindings_from_cc_generate_struct_and_union"}
has_bindings = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/has_bindings", package = "rs_bindings_from_cc_has_bindings"}
rs_type_kind = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/rs_type_kind", package = "rs_bindings_from_cc_rs_type_kind"}
arc_anyhow = { path = "../../../../cargo/common/arc_anyhow"}
code_gen_utils = { path = "../../../../cargo/common/code_gen_utils"}
crubit_abi_type = { path = "../../../../cargo/common/crubit_abi_type"}
crubit_feature = { path = "../../../../cargo/common/crubit_feature"}
dyn_format = { path = "../../../../cargo/common/dyn_format"}
error_report = { path = "../../../../cargo/common/error_report"}
errors = { path = "../../../../cargo/common/errors"}
ffi_types = { path = "../../../../cargo/common/ffi_types"}
token_stream_printer = { path = "../../../../cargo/common/token_stream_printer"}
ir = { path = "../../../../cargo/rs_bindings_from_cc/ir", package = "rs_bindings_from_cc_ir"}
database = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/database/database", package = "rs_bindings_from_cc_database"}
flagset.workspace = true
itertools.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
unicode-ident.workspace = true
[dev-dependencies]
multiplatform_ir_testing = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/multiplatform_ir_testing", package = "rs_bindings_from_cc_multiplatform_ir_testing"}
test_generators = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/test_generators", package = "rs_bindings_from_cc_test_generators"}
arc_anyhow = { path = "../../../../cargo/common/arc_anyhow"}
crubit_feature = { path = "../../../../cargo/common/crubit_feature"}
multiplatform_testing = { path = "../../../../cargo/common/multiplatform_testing"}
token_stream_matchers = { path = "../../../../cargo/common/token_stream_matchers"}
token_stream_printer = { path = "../../../../cargo/common/token_stream_printer"}
ir = { path = "../../../../cargo/rs_bindings_from_cc/ir", package = "rs_bindings_from_cc_ir"}
ir_matchers = { path = "../../../../cargo/rs_bindings_from_cc/ir_matchers", package = "rs_bindings_from_cc_ir_matchers"}
ir_testing = { path = "../../../../cargo/rs_bindings_from_cc/ir_testing", package = "rs_bindings_from_cc_ir_testing"}
database = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/database/database", package = "rs_bindings_from_cc_database"}
googletest.workspace = true
proc-macro2.workspace = true
quote.workspace = true
static_assertions.workspace = true
syn.workspace = true
