# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Automatically @generated Cargo.toml for the Rust crate rs_bindings_from_cc_has_bindings.

[package]
name = "rs_bindings_from_cc_has_bindings"
edition = "2021"

[lib]
path = "../../../../rs_bindings_from_cc/generate_bindings/has_bindings.rs"

[dependencies]
arc_anyhow = { path = "../../../../cargo/common/arc_anyhow"}
crubit_feature = { path = "../../../../cargo/common/crubit_feature"}
ir = { path = "../../../../cargo/rs_bindings_from_cc/ir"}
database = { path = "../../../../cargo/rs_bindings_from_cc/generate_bindings/database/database", package = "rs_bindings_from_cc_database"}
