# Part of the Crubit project, under the Apache License v2.0 with LLVM
# Exceptions. See /LICENSE for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Automatically @generated Cargo.toml for the cc_library rs_bindings_from_cc_impl_sys.

[package]
name = "rs_bindings_from_cc_impl_sys"
edition.workspace = true
license-file.workspace = true
repository.workspace = true
categories.workspace = true

build = "build.rs"

[lib]
path = "lib.rs"

[dependencies]
cc_ir_sys = { path = "../../../cargo/rs_bindings_from_cc/cc_ir_sys", package = "rs_bindings_from_cc_cc_ir_sys"}
cmdline_sys = { path = "../../../cargo/rs_bindings_from_cc/cmdline_sys", package = "rs_bindings_from_cc_cmdline_sys"}
collect_namespaces_sys = { path = "../../../cargo/rs_bindings_from_cc/collect_namespaces_sys", package = "rs_bindings_from_cc_collect_namespaces_sys"}
generate_bindings_and_metadata_sys = { path = "../../../cargo/rs_bindings_from_cc/generate_bindings_and_metadata_sys", package = "rs_bindings_from_cc_generate_bindings_and_metadata_sys"}
file_io_sys = { path = "../../../cargo/common/file_io_sys"}


[build-dependencies]
crubit_build = { path =  "../../../cargo/build"}
